#!/usr/bin/env python2
# written by Moses Arocha

import os

# define the function blocks
def firewall():
    print "You typed zero.\n"

def addUser():
    print "n is a perfect square\n"

def deletingUser():
    print "n is an even number\n"

def blockingPorts():
    print "n is a prime number\n"

# map the inputs to the function blocks

