#!/usr/bin/env python2
# written by Moses Arocha

import os

# define the function blocks
def firewall():
    RunFireWallRules = os.system('sudo ufw status')
    print RunFireWallRules

def addUser():
    print "n is a perfect square\n"

def deletingUser():
    print "n is an even number\n"

# map the inputs to the function blocks

ipVar = raw_input(" Please Insert IP Address: ")

print ("\n\n In Compliance with the rules of Cyber Patriot, which Script Do You wish to Run?\n\n)

choice = int(raw_input("\t 1. Firewall Setup \n\t 2. AddUser \n\t 3. DeleteUser")

if 1 == choice:
    firewall()

elif 2 == choice:
    addUser()
    
elif 3 == choice:
    deletingUser()
    
